### ISSUE TITLE
希望能增加对Vector皮肤的支持

### ISSUE THREAD

**Issue by TeoZler** [AzumWatson/moegirl-comment#10]
目前的插件只在使用MoeSkin皮肤时生效，希望能支持Vector皮肤

**Comment by AzumWatson** [comment]
萌娘百科可以切换皮肤吗，我都不知道欸。

**Comment by TeoZler** [comment]
https://zh.moegirl.org.cn/Special:%E5%8F%82%E6%95%B0%E8%AE%BE%E7%BD%AE#mw-prefsection-rendering
在这里可以更换皮肤

题外话，Vector似乎广告更少一些（

**Comment by AzumWatson** [comment]
已经增加了 对 Vector 皮肤的支持
